### PR TITLE
fix: use refresh token if available

### LINKED ISSUE #92: New login mode with tokens cache seems to ignore refreshToken
After a successful `1d login`, I get a valid `.auth.json` in the current working directory, and all operations work as expected. 

After the `accessToken` has expired, though, every further attempt to execute an operation fails with `'Access token has expired.'` So, apparently, the `refreshToken` in `.auth.json` is ignored and another `1d login` is required.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #92

### CODE REVIEW

File: src/client.js [hunk 1]
```diff
@@ -69,6 +68,15 @@ async function getOneDriveClient() {
...
     // ignore
   }
+
+  let {
+    AZURE_APP_REFRESH_TOKEN: refreshToken = '',
+  } = process.env;
+
+  if (!refreshToken && tokens.length) {
+    refreshToken = tokens[0].refreshToken;
+  }
```
Comment (dominique-pfister) [inline src/client.js:78]: If no `refreshToken` was specified, use a cached one if available. This changes the `AuthenticationContext` API being called from `acquireTokenWithClientCredentials` to `acquireTokenWithRefreshToken`

**Review by tripodsan — APPROVED** [review]
I think this needs even more refinement....but for now, this is certainly a good fix.
